version: '3.4'
x-env:
# 全局变量设置
  environment: &env
    USER: admin
    # Rclone远程控制用户名。
    PASSWORD: password
    # Rclone远程密码，同时也是Aria2的RPC密钥，务必设置为强密码。
    PUID: 0
    PGID: 0
    # 设置用户uid和gid，如需以非特权用户运行容器内进程，设置为1000以上即可。
    # 如果使用非特权用户运行，注意data数据卷的权限，容器启动时会自动修正config数据卷的权限。
    # 但data数据卷下文件数量可能很大，为避免影响启动速度需要手动设置权限。
    TZ: Asia/Shanghai
    # 指定时区。UTC为标准时间。
x-global: &global
# 其它全局设置
  volumes:
    - ~/data:/mnt/data
    # 下载数据存放目录。将~/data换成你在host上想指定的目录。
    - ~/config:/mnt/config
    # 配置文件存放目录。将~/config换成你在host上想指定的目录。
  restart: unless-stopped
  logging:
    driver: "journald"
    # 个人偏好journald自动管理日志。
    options:
      tag: "{{.Name}}"
      # 给日志添加容器名(container_name)的tag。
services:
  aria2:
    <<: *global
    image: ghcr.io/wy580477/aria2-container-for-rclone:latest
    container_name: aria2
    network_mode: host
    # 建议对docker不熟悉的用户选择host网络模式。
    environment:
      <<: *env
      RPC_PORT: 6800
      # Aria2远程RPC服务端口。
      POST_MODE: copy_remote
      # Aria2自动化模式，dummy模式为无操作，move模式为下载及做种完成后移动到本地finished目录。
      # move_remote模式为下载及做种完成后先移动到本地data数据卷下finished目录，然后移动到rclone远程存储。
      # move_remote_only模式为下载及做种完成后移动到rclone原创存储。
      # copy_remote_first模式为下载完成后立即复制到rclone原创存储，BT任务在做种前即触发。
      # copy_remote模式为下载及做种完成后先移动到本地data数据卷下finished目录，然后复制到rclone远程存储。
      # custom模式为自行设置aria2配置文件触发脚本选项。
      CLEAN_UNFINISHED_FAILED_TASK_FILES: "true"
      # 删除失败和在下载完成之前移除的任务文件。POST_MODE变量设置为Custom时，此项无效。
      AUTO_DRIVE_NAME: "true"
      # 设置为"true"会从rclone.conf文件第一行中提取Rclone远程存储配置名称。
      # 否则需要在config数据卷/aria2/script.conf文件中手动指定Rclone远程存储配置名称。
      RCLONE_ADDR: http://localhost:56802
      # Rclone Remote Control地址，默认值适用于host网络模式。
      # 如果使用bridge网络，需要改为"http://rclone:5572"。
    command:
      - --dht-listen-port=51413
      # DHT监听端口。
      - --listen-port=51413
      # BT监听端口。建议与上一项设置为同一端口，防火墙放行tcp和udp流量。
      - --rpc-listen-all=false
      # 是否接受来自外部ip的rpc连接，仅建议在家庭局域网环境内可设置为true，便于直接访问。
      # 如果通过Web服务反代，可以设置为false。
      - --disable-ipv6=true
      # 是否禁止ipv6。
      - --enable-dht6=false
      # 是否启用dht ipv6网络。
      - --show-console-readout=false
      # 禁止控制台输出信息，可以解决日志被刷屏问题，不会影响与Rclone联动相关信息的日志。
      - --enable-mmap=true
      # 可以添加更多运行参数，将覆盖Aria2配置文件中的相同选项。更多信息详见官网：https://aria2.github.io/manual/en/html/aria2c.html
  rclone_daemon:
    <<: *global
    image: ghcr.io/wy580477/rclone-daemon-container:latest
    container_name: rclone_daemon
    hostname: rclone
    environment:
      <<: *env
    ports:
      - "127.0.0.1:56802:5572"
      # 如果需要外部ip直接访问RC功能，设置为"56802:5572",建议仅在家庭局域网中使用。
    command:
      - --rc-web-gui
      # 自动下载Rclone Web UI，并使用内置http服务器在RC端口提供服务。
   #  - --rc-serve
      # 启用内置的http服务器在RC端口提供远程存储浏览，和上面的选项二选一。
      - --config /mnt/config/rclone.conf
      - --rc-allow-origin=*
      - --use-mmap
      - --buffer-size 4M
      # 单个文件传输内存缓冲区大小。
      - --transfers 4
      # 单任务并发传输数量。此项和上面一项默认设置适用于512M内存低配host，高配host可适当提高。
    # - --copy-links
      # 传输符号链接目标文件/目录。
      # 还可以添加更多运行参数，详见https://rclone.org/flags/
